/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSignOutRouteImport } from './routes/_protected/sign-out'
import { Route as ProtectedProduct_launchboardRouteImport } from './routes/_protected/product_launchboard'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as ProtectedfilerDepartment_add_clientIndexRouteImport } from './routes/_protected/(filer)/department_add_client/index'
import { Route as ProtectedfilerDashboard_filerIndexRouteImport } from './routes/_protected/(filer)/dashboard_filer/index'
import { Route as ProtectedfilerDashboardIndexRouteImport } from './routes/_protected/(filer)/dashboard/index'
import { Route as ProtectedfilerAssesseeEditRouteImport } from './routes/_protected/(filer)/assessee/edit'
import { Route as ProtectedfilerAssesseeAddRouteImport } from './routes/_protected/(filer)/assessee/add'

const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSigninLazyRouteImport = createFileRoute('/(auth)/signin')()
const authSignUpLazyRouteImport = createFileRoute('/(auth)/sign-up')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSigninLazyRoute = authSigninLazyRouteImport
  .update({
    id: '/(auth)/signin',
    path: '/signin',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/signin.lazy').then((d) => d.Route))
const authSignUpLazyRoute = authSignUpLazyRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const ProtectedSignOutRoute = ProtectedSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProduct_launchboardRoute =
  ProtectedProduct_launchboardRouteImport.update({
    id: '/product_launchboard',
    path: '/product_launchboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedfilerDepartment_add_clientIndexRoute =
  ProtectedfilerDepartment_add_clientIndexRouteImport.update({
    id: '/(filer)/department_add_client/',
    path: '/department_add_client/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerDashboard_filerIndexRoute =
  ProtectedfilerDashboard_filerIndexRouteImport.update({
    id: '/(filer)/dashboard_filer/',
    path: '/dashboard_filer/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerDashboardIndexRoute =
  ProtectedfilerDashboardIndexRouteImport.update({
    id: '/(filer)/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerAssesseeEditRoute =
  ProtectedfilerAssesseeEditRouteImport.update({
    id: '/(filer)/assessee/edit',
    path: '/assessee/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerAssesseeAddRoute =
  ProtectedfilerAssesseeAddRouteImport.update({
    id: '/(filer)/assessee/add',
    path: '/assessee/add',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/sign-out': typeof ProtectedSignOutRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/dashboard': typeof ProtectedfilerDashboardIndexRoute
  '/dashboard_filer': typeof ProtectedfilerDashboard_filerIndexRoute
  '/department_add_client': typeof ProtectedfilerDepartment_add_clientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/sign-out': typeof ProtectedSignOutRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/sign-up': typeof authSignUpLazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/dashboard': typeof ProtectedfilerDashboardIndexRoute
  '/dashboard_filer': typeof ProtectedfilerDashboard_filerIndexRoute
  '/department_add_client': typeof ProtectedfilerDepartment_add_clientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/_protected/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/_protected/sign-out': typeof ProtectedSignOutRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/sign-up': typeof authSignUpLazyRoute
  '/(auth)/signin': typeof authSigninLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_protected/(filer)/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/_protected/(filer)/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/_protected/(filer)/dashboard/': typeof ProtectedfilerDashboardIndexRoute
  '/_protected/(filer)/dashboard_filer/': typeof ProtectedfilerDashboard_filerIndexRoute
  '/_protected/(filer)/department_add_client/': typeof ProtectedfilerDepartment_add_clientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/product_launchboard'
    | '/sign-out'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/assessee/add'
    | '/assessee/edit'
    | '/dashboard'
    | '/dashboard_filer'
    | '/department_add_client'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/product_launchboard'
    | '/sign-out'
    | '/forgot-password'
    | '/sign-in-2'
    | '/sign-up'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/assessee/add'
    | '/assessee/edit'
    | '/dashboard'
    | '/dashboard_filer'
    | '/department_add_client'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/_protected/product_launchboard'
    | '/_protected/sign-out'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(auth)/signin'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_protected/(filer)/assessee/add'
    | '/_protected/(filer)/assessee/edit'
    | '/_protected/(filer)/dashboard/'
    | '/_protected/(filer)/dashboard_filer/'
    | '/_protected/(filer)/department_add_client/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSignUpLazyRoute: typeof authSignUpLazyRoute
  authSigninLazyRoute: typeof authSigninLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sign-out': {
      id: '/_protected/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof ProtectedSignOutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/product_launchboard': {
      id: '/_protected/product_launchboard'
      path: '/product_launchboard'
      fullPath: '/product_launchboard'
      preLoaderRoute: typeof ProtectedProduct_launchboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/(filer)/department_add_client/': {
      id: '/_protected/(filer)/department_add_client/'
      path: '/department_add_client'
      fullPath: '/department_add_client'
      preLoaderRoute: typeof ProtectedfilerDepartment_add_clientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/dashboard_filer/': {
      id: '/_protected/(filer)/dashboard_filer/'
      path: '/dashboard_filer'
      fullPath: '/dashboard_filer'
      preLoaderRoute: typeof ProtectedfilerDashboard_filerIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/dashboard/': {
      id: '/_protected/(filer)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedfilerDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/assessee/edit': {
      id: '/_protected/(filer)/assessee/edit'
      path: '/assessee/edit'
      fullPath: '/assessee/edit'
      preLoaderRoute: typeof ProtectedfilerAssesseeEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/assessee/add': {
      id: '/_protected/(filer)/assessee/add'
      path: '/assessee/add'
      fullPath: '/assessee/add'
      preLoaderRoute: typeof ProtectedfilerAssesseeAddRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedProduct_launchboardRoute: typeof ProtectedProduct_launchboardRoute
  ProtectedSignOutRoute: typeof ProtectedSignOutRoute
  ProtectedfilerAssesseeAddRoute: typeof ProtectedfilerAssesseeAddRoute
  ProtectedfilerAssesseeEditRoute: typeof ProtectedfilerAssesseeEditRoute
  ProtectedfilerDashboardIndexRoute: typeof ProtectedfilerDashboardIndexRoute
  ProtectedfilerDashboard_filerIndexRoute: typeof ProtectedfilerDashboard_filerIndexRoute
  ProtectedfilerDepartment_add_clientIndexRoute: typeof ProtectedfilerDepartment_add_clientIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProduct_launchboardRoute: ProtectedProduct_launchboardRoute,
  ProtectedSignOutRoute: ProtectedSignOutRoute,
  ProtectedfilerAssesseeAddRoute: ProtectedfilerAssesseeAddRoute,
  ProtectedfilerAssesseeEditRoute: ProtectedfilerAssesseeEditRoute,
  ProtectedfilerDashboardIndexRoute: ProtectedfilerDashboardIndexRoute,
  ProtectedfilerDashboard_filerIndexRoute:
    ProtectedfilerDashboard_filerIndexRoute,
  ProtectedfilerDepartment_add_clientIndexRoute:
    ProtectedfilerDepartment_add_clientIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSignUpLazyRoute: authSignUpLazyRoute,
  authSigninLazyRoute: authSigninLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
