/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedSignOutRouteImport } from './routes/_protected/sign-out'
import { Route as ProtectedProduct_launchboardRouteImport } from './routes/_protected/product_launchboard'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as ProtectedAdministrationLayoutRouteImport } from './routes/_protected/administration/_layout'
import { Route as ProtectedauthChangePasswordRouteImport } from './routes/_protected/(auth)/change-password'
import { Route as ProtectedSupportHelpIndexRouteImport } from './routes/_protected/support/help/index'
import { Route as ProtectedfilerStartIndexRouteImport } from './routes/_protected/(filer)/start/index'
import { Route as ProtectedfilerDepartment_add_clientIndexRouteImport } from './routes/_protected/(filer)/department_add_client/index'
import { Route as ProtectedfilerDashboard_filerIndexRouteImport } from './routes/_protected/(filer)/dashboard_filer/index'
import { Route as ProtectedfilerDashboardIndexRouteImport } from './routes/_protected/(filer)/dashboard/index'
import { Route as ProtectedauthVerifyPanIndexRouteImport } from './routes/_protected/(auth)/verify-pan/index'
import { Route as ProtectedauthMemberIndexRouteImport } from './routes/_protected/(auth)/member/index'
import { Route as ProtectedauthAddtaxformIndexRouteImport } from './routes/_protected/(auth)/addtaxform/index'
import { Route as ProtectedMastersOrganizationLayoutRouteImport } from './routes/_protected/masters/organization/_layout'
import { Route as ProtectedfilerAssesseeHeyassesseeRouteImport } from './routes/_protected/(filer)/assessee/heyassessee'
import { Route as ProtectedfilerAssesseeEditRouteImport } from './routes/_protected/(filer)/assessee/edit'
import { Route as ProtectedfilerAssesseeAddRouteImport } from './routes/_protected/(filer)/assessee/add'
import { Route as ProtectedauthUserFiscalYearLayoutRouteImport } from './routes/_protected/(auth)/user-fiscal-year/_layout'
import { Route as ProtectedauthProfileIndexRouteImport } from './routes/_protected/(auth)/profile/index.'
import { Route as ProtectedAdministrationLayoutPermissionIndexRouteImport } from './routes/_protected/administration/_layout/permission/index'
import { Route as ProtectedAdministrationLayoutApp_module_featureIndexRouteImport } from './routes/_protected/administration/_layout/app_module_feature/index'
import { Route as ProtectedAdministrationLayoutApp_moduleIndexRouteImport } from './routes/_protected/administration/_layout/app_module/index'
import { Route as ProtectedauthUserFiscalYearLayoutIndexRouteImport } from './routes/_protected/(auth)/user-fiscal-year/_layout/index'
import { Route as ProtectedAdministrationLayoutUserLayoutRouteImport } from './routes/_protected/administration/_layout/user/_layout'
import { Route as ProtectedAdministrationLayoutRoleLayoutRouteImport } from './routes/_protected/administration/_layout/role/_layout'
import { Route as ProtectedMastersOrganizationLayoutBranchIndexRouteImport } from './routes/_protected/masters/organization/_layout/branch/index'
import { Route as ProtectedAdministrationLayoutUserLayoutIndexRouteImport } from './routes/_protected/administration/_layout/user/_layout/index'
import { Route as ProtectedAdministrationLayoutRoleLayoutIndexRouteImport } from './routes/_protected/administration/_layout/role/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutStateLayoutRouteImport } from './routes/_protected/masters/organization/_layout/state/_layout'
import { Route as ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteImport } from './routes/_protected/masters/organization/_layout/fiscal_year/_layout'
import { Route as ProtectedMastersOrganizationLayoutCurrencyLayoutRouteImport } from './routes/_protected/masters/organization/_layout/currency/_layout'
import { Route as ProtectedMastersOrganizationLayoutCountryLayoutRouteImport } from './routes/_protected/masters/organization/_layout/country/_layout'
import { Route as ProtectedMastersOrganizationLayoutCompanyLayoutRouteImport } from './routes/_protected/masters/organization/_layout/company/_layout'
import { Route as ProtectedAdministrationLayoutUserLayoutIdRouteImport } from './routes/_protected/administration/_layout/user/_layout/$id'
import { Route as ProtectedMastersOrganizationLayoutStateLayoutIndexRouteImport } from './routes/_protected/masters/organization/_layout/state/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRouteImport } from './routes/_protected/masters/organization/_layout/fiscal_year/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRouteImport } from './routes/_protected/masters/organization/_layout/currency/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutCountryLayoutIndexRouteImport } from './routes/_protected/masters/organization/_layout/country/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutCompanyLayoutIndexRouteImport } from './routes/_protected/masters/organization/_layout/company/_layout/index'
import { Route as ProtectedMastersOrganizationLayoutStateLayoutIdRouteImport } from './routes/_protected/masters/organization/_layout/state/_layout/$id'
import { Route as ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRouteImport } from './routes/_protected/masters/organization/_layout/fiscal_year/_layout/$id'
import { Route as ProtectedMastersOrganizationLayoutCurrencyLayoutIdRouteImport } from './routes/_protected/masters/organization/_layout/currency/_layout/$id'
import { Route as ProtectedMastersOrganizationLayoutCountryLayoutIdRouteImport } from './routes/_protected/masters/organization/_layout/country/_layout/$id'
import { Route as ProtectedMastersOrganizationLayoutCompanyLayoutIdRouteImport } from './routes/_protected/masters/organization/_layout/company/_layout/$id'
import { Route as ProtectedAdministrationLayoutRoleLayoutIdModuleRouteImport } from './routes/_protected/administration/_layout/role/_layout/$id/_module'
import { Route as ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRouteImport } from './routes/_protected/administration/_layout/role/_layout/$id/_module/index'
import { Route as ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRouteImport } from './routes/_protected/administration/_layout/role/_layout/$id/_module/$moduleid'

const errors503LazyRouteImport = createFileRoute('/(errors)/503')()
const errors500LazyRouteImport = createFileRoute('/(errors)/500')()
const errors404LazyRouteImport = createFileRoute('/(errors)/404')()
const errors403LazyRouteImport = createFileRoute('/(errors)/403')()
const errors401LazyRouteImport = createFileRoute('/(errors)/401')()
const authSigninLazyRouteImport = createFileRoute('/(auth)/signin')()
const authSignIn2LazyRouteImport = createFileRoute('/(auth)/sign-in-2')()
const authForgotPasswordLazyRouteImport = createFileRoute(
  '/(auth)/forgot-password',
)()

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503LazyRoute = errors503LazyRouteImport
  .update({
    id: '/(errors)/503',
    path: '/503',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/503.lazy').then((d) => d.Route))
const errors500LazyRoute = errors500LazyRouteImport
  .update({
    id: '/(errors)/500',
    path: '/500',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/500.lazy').then((d) => d.Route))
const errors404LazyRoute = errors404LazyRouteImport
  .update({
    id: '/(errors)/404',
    path: '/404',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/404.lazy').then((d) => d.Route))
const errors403LazyRoute = errors403LazyRouteImport
  .update({
    id: '/(errors)/403',
    path: '/403',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/403.lazy').then((d) => d.Route))
const errors401LazyRoute = errors401LazyRouteImport
  .update({
    id: '/(errors)/401',
    path: '/401',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(errors)/401.lazy').then((d) => d.Route))
const authSigninLazyRoute = authSigninLazyRouteImport
  .update({
    id: '/(auth)/signin',
    path: '/signin',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/signin.lazy').then((d) => d.Route))
const authSignIn2LazyRoute = authSignIn2LazyRouteImport
  .update({
    id: '/(auth)/sign-in-2',
    path: '/sign-in-2',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-in-2.lazy').then((d) => d.Route))
const authForgotPasswordLazyRoute = authForgotPasswordLazyRouteImport
  .update({
    id: '/(auth)/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() =>
    import('./routes/(auth)/forgot-password.lazy').then((d) => d.Route),
  )
const ProtectedSignOutRoute = ProtectedSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProduct_launchboardRoute =
  ProtectedProduct_launchboardRouteImport.update({
    id: '/product_launchboard',
    path: '/product_launchboard',
    getParentRoute: () => ProtectedRoute,
  } as any)
const authSignUpRoute = authSignUpRouteImport
  .update({
    id: '/(auth)/sign-up',
    path: '/sign-up',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(auth)/sign-up.lazy').then((d) => d.Route))
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedAdministrationLayoutRoute =
  ProtectedAdministrationLayoutRouteImport.update({
    id: '/administration/_layout',
    path: '/administration',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthChangePasswordRoute =
  ProtectedauthChangePasswordRouteImport.update({
    id: '/(auth)/change-password',
    path: '/change-password',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSupportHelpIndexRoute =
  ProtectedSupportHelpIndexRouteImport.update({
    id: '/support/help/',
    path: '/support/help/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerStartIndexRoute =
  ProtectedfilerStartIndexRouteImport.update({
    id: '/(filer)/start/',
    path: '/start/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerDepartment_add_clientIndexRoute =
  ProtectedfilerDepartment_add_clientIndexRouteImport.update({
    id: '/(filer)/department_add_client/',
    path: '/department_add_client/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerDashboard_filerIndexRoute =
  ProtectedfilerDashboard_filerIndexRouteImport.update({
    id: '/(filer)/dashboard_filer/',
    path: '/dashboard_filer/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerDashboardIndexRoute =
  ProtectedfilerDashboardIndexRouteImport.update({
    id: '/(filer)/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthVerifyPanIndexRoute =
  ProtectedauthVerifyPanIndexRouteImport.update({
    id: '/(auth)/verify-pan/',
    path: '/verify-pan/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthMemberIndexRoute =
  ProtectedauthMemberIndexRouteImport.update({
    id: '/(auth)/member/',
    path: '/member/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthAddtaxformIndexRoute =
  ProtectedauthAddtaxformIndexRouteImport.update({
    id: '/(auth)/addtaxform/',
    path: '/addtaxform/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedMastersOrganizationLayoutRoute =
  ProtectedMastersOrganizationLayoutRouteImport.update({
    id: '/masters/organization/_layout',
    path: '/masters/organization',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerAssesseeHeyassesseeRoute =
  ProtectedfilerAssesseeHeyassesseeRouteImport.update({
    id: '/(filer)/assessee/heyassessee',
    path: '/assessee/heyassessee',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerAssesseeEditRoute =
  ProtectedfilerAssesseeEditRouteImport.update({
    id: '/(filer)/assessee/edit',
    path: '/assessee/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedfilerAssesseeAddRoute =
  ProtectedfilerAssesseeAddRouteImport.update({
    id: '/(filer)/assessee/add',
    path: '/assessee/add',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthUserFiscalYearLayoutRoute =
  ProtectedauthUserFiscalYearLayoutRouteImport.update({
    id: '/(auth)/user-fiscal-year/_layout',
    path: '/user-fiscal-year',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedauthProfileIndexRoute =
  ProtectedauthProfileIndexRouteImport.update({
    id: '/(auth)/profile/index/',
    path: '/profile/index/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedAdministrationLayoutPermissionIndexRoute =
  ProtectedAdministrationLayoutPermissionIndexRouteImport.update({
    id: '/permission/',
    path: '/permission/',
    getParentRoute: () => ProtectedAdministrationLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutApp_module_featureIndexRoute =
  ProtectedAdministrationLayoutApp_module_featureIndexRouteImport.update({
    id: '/app_module_feature/',
    path: '/app_module_feature/',
    getParentRoute: () => ProtectedAdministrationLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutApp_moduleIndexRoute =
  ProtectedAdministrationLayoutApp_moduleIndexRouteImport.update({
    id: '/app_module/',
    path: '/app_module/',
    getParentRoute: () => ProtectedAdministrationLayoutRoute,
  } as any)
const ProtectedauthUserFiscalYearLayoutIndexRoute =
  ProtectedauthUserFiscalYearLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedauthUserFiscalYearLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutUserLayoutRoute =
  ProtectedAdministrationLayoutUserLayoutRouteImport.update({
    id: '/user/_layout',
    path: '/user',
    getParentRoute: () => ProtectedAdministrationLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutRoleLayoutRoute =
  ProtectedAdministrationLayoutRoleLayoutRouteImport.update({
    id: '/role/_layout',
    path: '/role',
    getParentRoute: () => ProtectedAdministrationLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutBranchIndexRoute =
  ProtectedMastersOrganizationLayoutBranchIndexRouteImport.update({
    id: '/branch/',
    path: '/branch/',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutUserLayoutIndexRoute =
  ProtectedAdministrationLayoutUserLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdministrationLayoutUserLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutRoleLayoutIndexRoute =
  ProtectedAdministrationLayoutRoleLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdministrationLayoutRoleLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutStateLayoutRoute =
  ProtectedMastersOrganizationLayoutStateLayoutRouteImport.update({
    id: '/state/_layout',
    path: '/state',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute =
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteImport.update({
    id: '/fiscal_year/_layout',
    path: '/fiscal_year',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCurrencyLayoutRoute =
  ProtectedMastersOrganizationLayoutCurrencyLayoutRouteImport.update({
    id: '/currency/_layout',
    path: '/currency',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCountryLayoutRoute =
  ProtectedMastersOrganizationLayoutCountryLayoutRouteImport.update({
    id: '/country/_layout',
    path: '/country',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCompanyLayoutRoute =
  ProtectedMastersOrganizationLayoutCompanyLayoutRouteImport.update({
    id: '/company/_layout',
    path: '/company',
    getParentRoute: () => ProtectedMastersOrganizationLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutUserLayoutIdRoute =
  ProtectedAdministrationLayoutUserLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedAdministrationLayoutUserLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutStateLayoutIndexRoute =
  ProtectedMastersOrganizationLayoutStateLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMastersOrganizationLayoutStateLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute =
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute =
  ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCurrencyLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute =
  ProtectedMastersOrganizationLayoutCountryLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCountryLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute =
  ProtectedMastersOrganizationLayoutCompanyLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCompanyLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutStateLayoutIdRoute =
  ProtectedMastersOrganizationLayoutStateLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedMastersOrganizationLayoutStateLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute =
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () =>
      ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute =
  ProtectedMastersOrganizationLayoutCurrencyLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCurrencyLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCountryLayoutIdRoute =
  ProtectedMastersOrganizationLayoutCountryLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCountryLayoutRoute,
  } as any)
const ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute =
  ProtectedMastersOrganizationLayoutCompanyLayoutIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => ProtectedMastersOrganizationLayoutCompanyLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutRoleLayoutIdModuleRoute =
  ProtectedAdministrationLayoutRoleLayoutIdModuleRouteImport.update({
    id: '/$id/_module',
    path: '/$id',
    getParentRoute: () => ProtectedAdministrationLayoutRoleLayoutRoute,
  } as any)
const ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute =
  ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedAdministrationLayoutRoleLayoutIdModuleRoute,
  } as any)
const ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute =
  ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRouteImport.update({
    id: '/$moduleid',
    path: '/$moduleid',
    getParentRoute: () => ProtectedAdministrationLayoutRoleLayoutIdModuleRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/sign-out': typeof ProtectedSignOutRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/change-password': typeof ProtectedauthChangePasswordRoute
  '/administration': typeof ProtectedAdministrationLayoutRouteWithChildren
  '/user-fiscal-year': typeof ProtectedauthUserFiscalYearLayoutRouteWithChildren
  '/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/assessee/heyassessee': typeof ProtectedfilerAssesseeHeyassesseeRoute
  '/masters/organization': typeof ProtectedMastersOrganizationLayoutRouteWithChildren
  '/addtaxform/': typeof ProtectedauthAddtaxformIndexRoute
  '/member/': typeof ProtectedauthMemberIndexRoute
  '/verify-pan/': typeof ProtectedauthVerifyPanIndexRoute
  '/dashboard/': typeof ProtectedfilerDashboardIndexRoute
  '/dashboard_filer/': typeof ProtectedfilerDashboard_filerIndexRoute
  '/department_add_client/': typeof ProtectedfilerDepartment_add_clientIndexRoute
  '/start/': typeof ProtectedfilerStartIndexRoute
  '/support/help/': typeof ProtectedSupportHelpIndexRoute
  '/administration/role': typeof ProtectedAdministrationLayoutRoleLayoutRouteWithChildren
  '/administration/user': typeof ProtectedAdministrationLayoutUserLayoutRouteWithChildren
  '/profile/index/': typeof ProtectedauthProfileIndexRoute
  '/user-fiscal-year/': typeof ProtectedauthUserFiscalYearLayoutIndexRoute
  '/administration/app_module/': typeof ProtectedAdministrationLayoutApp_moduleIndexRoute
  '/administration/app_module_feature/': typeof ProtectedAdministrationLayoutApp_module_featureIndexRoute
  '/administration/permission/': typeof ProtectedAdministrationLayoutPermissionIndexRoute
  '/administration/user/$id': typeof ProtectedAdministrationLayoutUserLayoutIdRoute
  '/masters/organization/company': typeof ProtectedMastersOrganizationLayoutCompanyLayoutRouteWithChildren
  '/masters/organization/country': typeof ProtectedMastersOrganizationLayoutCountryLayoutRouteWithChildren
  '/masters/organization/currency': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRouteWithChildren
  '/masters/organization/fiscal_year': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteWithChildren
  '/masters/organization/state': typeof ProtectedMastersOrganizationLayoutStateLayoutRouteWithChildren
  '/administration/role/': typeof ProtectedAdministrationLayoutRoleLayoutIndexRoute
  '/administration/user/': typeof ProtectedAdministrationLayoutUserLayoutIndexRoute
  '/masters/organization/branch/': typeof ProtectedMastersOrganizationLayoutBranchIndexRoute
  '/administration/role/$id': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRouteWithChildren
  '/masters/organization/company/$id': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute
  '/masters/organization/country/$id': typeof ProtectedMastersOrganizationLayoutCountryLayoutIdRoute
  '/masters/organization/currency/$id': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute
  '/masters/organization/fiscal_year/$id': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute
  '/masters/organization/state/$id': typeof ProtectedMastersOrganizationLayoutStateLayoutIdRoute
  '/masters/organization/company/': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute
  '/masters/organization/country/': typeof ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute
  '/masters/organization/currency/': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute
  '/masters/organization/fiscal_year/': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute
  '/masters/organization/state/': typeof ProtectedMastersOrganizationLayoutStateLayoutIndexRoute
  '/administration/role/$id/$moduleid': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute
  '/administration/role/$id/': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/sign-out': typeof ProtectedSignOutRoute
  '/forgot-password': typeof authForgotPasswordLazyRoute
  '/sign-in-2': typeof authSignIn2LazyRoute
  '/signin': typeof authSigninLazyRoute
  '/401': typeof errors401LazyRoute
  '/403': typeof errors403LazyRoute
  '/404': typeof errors404LazyRoute
  '/500': typeof errors500LazyRoute
  '/503': typeof errors503LazyRoute
  '/change-password': typeof ProtectedauthChangePasswordRoute
  '/administration': typeof ProtectedAdministrationLayoutRouteWithChildren
  '/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/assessee/heyassessee': typeof ProtectedfilerAssesseeHeyassesseeRoute
  '/masters/organization': typeof ProtectedMastersOrganizationLayoutRouteWithChildren
  '/addtaxform': typeof ProtectedauthAddtaxformIndexRoute
  '/member': typeof ProtectedauthMemberIndexRoute
  '/verify-pan': typeof ProtectedauthVerifyPanIndexRoute
  '/dashboard': typeof ProtectedfilerDashboardIndexRoute
  '/dashboard_filer': typeof ProtectedfilerDashboard_filerIndexRoute
  '/department_add_client': typeof ProtectedfilerDepartment_add_clientIndexRoute
  '/start': typeof ProtectedfilerStartIndexRoute
  '/support/help': typeof ProtectedSupportHelpIndexRoute
  '/profile/index': typeof ProtectedauthProfileIndexRoute
  '/user-fiscal-year': typeof ProtectedauthUserFiscalYearLayoutIndexRoute
  '/administration/app_module': typeof ProtectedAdministrationLayoutApp_moduleIndexRoute
  '/administration/app_module_feature': typeof ProtectedAdministrationLayoutApp_module_featureIndexRoute
  '/administration/permission': typeof ProtectedAdministrationLayoutPermissionIndexRoute
  '/administration/user/$id': typeof ProtectedAdministrationLayoutUserLayoutIdRoute
  '/administration/role': typeof ProtectedAdministrationLayoutRoleLayoutIndexRoute
  '/administration/user': typeof ProtectedAdministrationLayoutUserLayoutIndexRoute
  '/masters/organization/branch': typeof ProtectedMastersOrganizationLayoutBranchIndexRoute
  '/masters/organization/company/$id': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute
  '/masters/organization/country/$id': typeof ProtectedMastersOrganizationLayoutCountryLayoutIdRoute
  '/masters/organization/currency/$id': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute
  '/masters/organization/fiscal_year/$id': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute
  '/masters/organization/state/$id': typeof ProtectedMastersOrganizationLayoutStateLayoutIdRoute
  '/masters/organization/company': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute
  '/masters/organization/country': typeof ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute
  '/masters/organization/currency': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute
  '/masters/organization/fiscal_year': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute
  '/masters/organization/state': typeof ProtectedMastersOrganizationLayoutStateLayoutIndexRoute
  '/administration/role/$id/$moduleid': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute
  '/administration/role/$id': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_protected/product_launchboard': typeof ProtectedProduct_launchboardRoute
  '/_protected/sign-out': typeof ProtectedSignOutRoute
  '/(auth)/forgot-password': typeof authForgotPasswordLazyRoute
  '/(auth)/sign-in-2': typeof authSignIn2LazyRoute
  '/(auth)/signin': typeof authSigninLazyRoute
  '/(errors)/401': typeof errors401LazyRoute
  '/(errors)/403': typeof errors403LazyRoute
  '/(errors)/404': typeof errors404LazyRoute
  '/(errors)/500': typeof errors500LazyRoute
  '/(errors)/503': typeof errors503LazyRoute
  '/_protected/(auth)/change-password': typeof ProtectedauthChangePasswordRoute
  '/_protected/administration/_layout': typeof ProtectedAdministrationLayoutRouteWithChildren
  '/_protected/(auth)/user-fiscal-year/_layout': typeof ProtectedauthUserFiscalYearLayoutRouteWithChildren
  '/_protected/(filer)/assessee/add': typeof ProtectedfilerAssesseeAddRoute
  '/_protected/(filer)/assessee/edit': typeof ProtectedfilerAssesseeEditRoute
  '/_protected/(filer)/assessee/heyassessee': typeof ProtectedfilerAssesseeHeyassesseeRoute
  '/_protected/masters/organization/_layout': typeof ProtectedMastersOrganizationLayoutRouteWithChildren
  '/_protected/(auth)/addtaxform/': typeof ProtectedauthAddtaxformIndexRoute
  '/_protected/(auth)/member/': typeof ProtectedauthMemberIndexRoute
  '/_protected/(auth)/verify-pan/': typeof ProtectedauthVerifyPanIndexRoute
  '/_protected/(filer)/dashboard/': typeof ProtectedfilerDashboardIndexRoute
  '/_protected/(filer)/dashboard_filer/': typeof ProtectedfilerDashboard_filerIndexRoute
  '/_protected/(filer)/department_add_client/': typeof ProtectedfilerDepartment_add_clientIndexRoute
  '/_protected/(filer)/start/': typeof ProtectedfilerStartIndexRoute
  '/_protected/support/help/': typeof ProtectedSupportHelpIndexRoute
  '/_protected/administration/_layout/role/_layout': typeof ProtectedAdministrationLayoutRoleLayoutRouteWithChildren
  '/_protected/administration/_layout/user/_layout': typeof ProtectedAdministrationLayoutUserLayoutRouteWithChildren
  '/_protected/(auth)/profile/index/': typeof ProtectedauthProfileIndexRoute
  '/_protected/(auth)/user-fiscal-year/_layout/': typeof ProtectedauthUserFiscalYearLayoutIndexRoute
  '/_protected/administration/_layout/app_module/': typeof ProtectedAdministrationLayoutApp_moduleIndexRoute
  '/_protected/administration/_layout/app_module_feature/': typeof ProtectedAdministrationLayoutApp_module_featureIndexRoute
  '/_protected/administration/_layout/permission/': typeof ProtectedAdministrationLayoutPermissionIndexRoute
  '/_protected/administration/_layout/user/_layout/$id': typeof ProtectedAdministrationLayoutUserLayoutIdRoute
  '/_protected/masters/organization/_layout/company/_layout': typeof ProtectedMastersOrganizationLayoutCompanyLayoutRouteWithChildren
  '/_protected/masters/organization/_layout/country/_layout': typeof ProtectedMastersOrganizationLayoutCountryLayoutRouteWithChildren
  '/_protected/masters/organization/_layout/currency/_layout': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRouteWithChildren
  '/_protected/masters/organization/_layout/fiscal_year/_layout': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteWithChildren
  '/_protected/masters/organization/_layout/state/_layout': typeof ProtectedMastersOrganizationLayoutStateLayoutRouteWithChildren
  '/_protected/administration/_layout/role/_layout/': typeof ProtectedAdministrationLayoutRoleLayoutIndexRoute
  '/_protected/administration/_layout/user/_layout/': typeof ProtectedAdministrationLayoutUserLayoutIndexRoute
  '/_protected/masters/organization/_layout/branch/': typeof ProtectedMastersOrganizationLayoutBranchIndexRoute
  '/_protected/administration/_layout/role/_layout/$id/_module': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRouteWithChildren
  '/_protected/masters/organization/_layout/company/_layout/$id': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute
  '/_protected/masters/organization/_layout/country/_layout/$id': typeof ProtectedMastersOrganizationLayoutCountryLayoutIdRoute
  '/_protected/masters/organization/_layout/currency/_layout/$id': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute
  '/_protected/masters/organization/_layout/fiscal_year/_layout/$id': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute
  '/_protected/masters/organization/_layout/state/_layout/$id': typeof ProtectedMastersOrganizationLayoutStateLayoutIdRoute
  '/_protected/masters/organization/_layout/company/_layout/': typeof ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute
  '/_protected/masters/organization/_layout/country/_layout/': typeof ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute
  '/_protected/masters/organization/_layout/currency/_layout/': typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute
  '/_protected/masters/organization/_layout/fiscal_year/_layout/': typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute
  '/_protected/masters/organization/_layout/state/_layout/': typeof ProtectedMastersOrganizationLayoutStateLayoutIndexRoute
  '/_protected/administration/_layout/role/_layout/$id/_module/$moduleid': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute
  '/_protected/administration/_layout/role/_layout/$id/_module/': typeof ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/product_launchboard'
    | '/sign-out'
    | '/forgot-password'
    | '/sign-in-2'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/change-password'
    | '/administration'
    | '/user-fiscal-year'
    | '/assessee/add'
    | '/assessee/edit'
    | '/assessee/heyassessee'
    | '/masters/organization'
    | '/addtaxform/'
    | '/member/'
    | '/verify-pan/'
    | '/dashboard/'
    | '/dashboard_filer/'
    | '/department_add_client/'
    | '/start/'
    | '/support/help/'
    | '/administration/role'
    | '/administration/user'
    | '/profile/index/'
    | '/user-fiscal-year/'
    | '/administration/app_module/'
    | '/administration/app_module_feature/'
    | '/administration/permission/'
    | '/administration/user/$id'
    | '/masters/organization/company'
    | '/masters/organization/country'
    | '/masters/organization/currency'
    | '/masters/organization/fiscal_year'
    | '/masters/organization/state'
    | '/administration/role/'
    | '/administration/user/'
    | '/masters/organization/branch/'
    | '/administration/role/$id'
    | '/masters/organization/company/$id'
    | '/masters/organization/country/$id'
    | '/masters/organization/currency/$id'
    | '/masters/organization/fiscal_year/$id'
    | '/masters/organization/state/$id'
    | '/masters/organization/company/'
    | '/masters/organization/country/'
    | '/masters/organization/currency/'
    | '/masters/organization/fiscal_year/'
    | '/masters/organization/state/'
    | '/administration/role/$id/$moduleid'
    | '/administration/role/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/product_launchboard'
    | '/sign-out'
    | '/forgot-password'
    | '/sign-in-2'
    | '/signin'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/change-password'
    | '/administration'
    | '/assessee/add'
    | '/assessee/edit'
    | '/assessee/heyassessee'
    | '/masters/organization'
    | '/addtaxform'
    | '/member'
    | '/verify-pan'
    | '/dashboard'
    | '/dashboard_filer'
    | '/department_add_client'
    | '/start'
    | '/support/help'
    | '/profile/index'
    | '/user-fiscal-year'
    | '/administration/app_module'
    | '/administration/app_module_feature'
    | '/administration/permission'
    | '/administration/user/$id'
    | '/administration/role'
    | '/administration/user'
    | '/masters/organization/branch'
    | '/masters/organization/company/$id'
    | '/masters/organization/country/$id'
    | '/masters/organization/currency/$id'
    | '/masters/organization/fiscal_year/$id'
    | '/masters/organization/state/$id'
    | '/masters/organization/company'
    | '/masters/organization/country'
    | '/masters/organization/currency'
    | '/masters/organization/fiscal_year'
    | '/masters/organization/state'
    | '/administration/role/$id/$moduleid'
    | '/administration/role/$id'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_protected/product_launchboard'
    | '/_protected/sign-out'
    | '/(auth)/forgot-password'
    | '/(auth)/sign-in-2'
    | '/(auth)/signin'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_protected/(auth)/change-password'
    | '/_protected/administration/_layout'
    | '/_protected/(auth)/user-fiscal-year/_layout'
    | '/_protected/(filer)/assessee/add'
    | '/_protected/(filer)/assessee/edit'
    | '/_protected/(filer)/assessee/heyassessee'
    | '/_protected/masters/organization/_layout'
    | '/_protected/(auth)/addtaxform/'
    | '/_protected/(auth)/member/'
    | '/_protected/(auth)/verify-pan/'
    | '/_protected/(filer)/dashboard/'
    | '/_protected/(filer)/dashboard_filer/'
    | '/_protected/(filer)/department_add_client/'
    | '/_protected/(filer)/start/'
    | '/_protected/support/help/'
    | '/_protected/administration/_layout/role/_layout'
    | '/_protected/administration/_layout/user/_layout'
    | '/_protected/(auth)/profile/index/'
    | '/_protected/(auth)/user-fiscal-year/_layout/'
    | '/_protected/administration/_layout/app_module/'
    | '/_protected/administration/_layout/app_module_feature/'
    | '/_protected/administration/_layout/permission/'
    | '/_protected/administration/_layout/user/_layout/$id'
    | '/_protected/masters/organization/_layout/company/_layout'
    | '/_protected/masters/organization/_layout/country/_layout'
    | '/_protected/masters/organization/_layout/currency/_layout'
    | '/_protected/masters/organization/_layout/fiscal_year/_layout'
    | '/_protected/masters/organization/_layout/state/_layout'
    | '/_protected/administration/_layout/role/_layout/'
    | '/_protected/administration/_layout/user/_layout/'
    | '/_protected/masters/organization/_layout/branch/'
    | '/_protected/administration/_layout/role/_layout/$id/_module'
    | '/_protected/masters/organization/_layout/company/_layout/$id'
    | '/_protected/masters/organization/_layout/country/_layout/$id'
    | '/_protected/masters/organization/_layout/currency/_layout/$id'
    | '/_protected/masters/organization/_layout/fiscal_year/_layout/$id'
    | '/_protected/masters/organization/_layout/state/_layout/$id'
    | '/_protected/masters/organization/_layout/company/_layout/'
    | '/_protected/masters/organization/_layout/country/_layout/'
    | '/_protected/masters/organization/_layout/currency/_layout/'
    | '/_protected/masters/organization/_layout/fiscal_year/_layout/'
    | '/_protected/masters/organization/_layout/state/_layout/'
    | '/_protected/administration/_layout/role/_layout/$id/_module/$moduleid'
    | '/_protected/administration/_layout/role/_layout/$id/_module/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  authForgotPasswordLazyRoute: typeof authForgotPasswordLazyRoute
  authSignIn2LazyRoute: typeof authSignIn2LazyRoute
  authSigninLazyRoute: typeof authSigninLazyRoute
  errors401LazyRoute: typeof errors401LazyRoute
  errors403LazyRoute: typeof errors403LazyRoute
  errors404LazyRoute: typeof errors404LazyRoute
  errors500LazyRoute: typeof errors500LazyRoute
  errors503LazyRoute: typeof errors503LazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2LazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/sign-out': {
      id: '/_protected/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof ProtectedSignOutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/product_launchboard': {
      id: '/_protected/product_launchboard'
      path: '/product_launchboard'
      fullPath: '/product_launchboard'
      preLoaderRoute: typeof ProtectedProduct_launchboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/administration/_layout': {
      id: '/_protected/administration/_layout'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/change-password': {
      id: '/_protected/(auth)/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ProtectedauthChangePasswordRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/support/help/': {
      id: '/_protected/support/help/'
      path: '/support/help'
      fullPath: '/support/help/'
      preLoaderRoute: typeof ProtectedSupportHelpIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/start/': {
      id: '/_protected/(filer)/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof ProtectedfilerStartIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/department_add_client/': {
      id: '/_protected/(filer)/department_add_client/'
      path: '/department_add_client'
      fullPath: '/department_add_client/'
      preLoaderRoute: typeof ProtectedfilerDepartment_add_clientIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/dashboard_filer/': {
      id: '/_protected/(filer)/dashboard_filer/'
      path: '/dashboard_filer'
      fullPath: '/dashboard_filer/'
      preLoaderRoute: typeof ProtectedfilerDashboard_filerIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/dashboard/': {
      id: '/_protected/(filer)/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedfilerDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/verify-pan/': {
      id: '/_protected/(auth)/verify-pan/'
      path: '/verify-pan'
      fullPath: '/verify-pan/'
      preLoaderRoute: typeof ProtectedauthVerifyPanIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/member/': {
      id: '/_protected/(auth)/member/'
      path: '/member'
      fullPath: '/member/'
      preLoaderRoute: typeof ProtectedauthMemberIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/addtaxform/': {
      id: '/_protected/(auth)/addtaxform/'
      path: '/addtaxform'
      fullPath: '/addtaxform/'
      preLoaderRoute: typeof ProtectedauthAddtaxformIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/masters/organization/_layout': {
      id: '/_protected/masters/organization/_layout'
      path: '/masters/organization'
      fullPath: '/masters/organization'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/assessee/heyassessee': {
      id: '/_protected/(filer)/assessee/heyassessee'
      path: '/assessee/heyassessee'
      fullPath: '/assessee/heyassessee'
      preLoaderRoute: typeof ProtectedfilerAssesseeHeyassesseeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/assessee/edit': {
      id: '/_protected/(filer)/assessee/edit'
      path: '/assessee/edit'
      fullPath: '/assessee/edit'
      preLoaderRoute: typeof ProtectedfilerAssesseeEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(filer)/assessee/add': {
      id: '/_protected/(filer)/assessee/add'
      path: '/assessee/add'
      fullPath: '/assessee/add'
      preLoaderRoute: typeof ProtectedfilerAssesseeAddRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/user-fiscal-year/_layout': {
      id: '/_protected/(auth)/user-fiscal-year/_layout'
      path: '/user-fiscal-year'
      fullPath: '/user-fiscal-year'
      preLoaderRoute: typeof ProtectedauthUserFiscalYearLayoutRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/(auth)/profile/index/': {
      id: '/_protected/(auth)/profile/index/'
      path: '/profile/index'
      fullPath: '/profile/index/'
      preLoaderRoute: typeof ProtectedauthProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/administration/_layout/permission/': {
      id: '/_protected/administration/_layout/permission/'
      path: '/permission'
      fullPath: '/administration/permission/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutPermissionIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoute
    }
    '/_protected/administration/_layout/app_module_feature/': {
      id: '/_protected/administration/_layout/app_module_feature/'
      path: '/app_module_feature'
      fullPath: '/administration/app_module_feature/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutApp_module_featureIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoute
    }
    '/_protected/administration/_layout/app_module/': {
      id: '/_protected/administration/_layout/app_module/'
      path: '/app_module'
      fullPath: '/administration/app_module/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutApp_moduleIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoute
    }
    '/_protected/(auth)/user-fiscal-year/_layout/': {
      id: '/_protected/(auth)/user-fiscal-year/_layout/'
      path: '/'
      fullPath: '/user-fiscal-year/'
      preLoaderRoute: typeof ProtectedauthUserFiscalYearLayoutIndexRouteImport
      parentRoute: typeof ProtectedauthUserFiscalYearLayoutRoute
    }
    '/_protected/administration/_layout/user/_layout': {
      id: '/_protected/administration/_layout/user/_layout'
      path: '/user'
      fullPath: '/administration/user'
      preLoaderRoute: typeof ProtectedAdministrationLayoutUserLayoutRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoute
    }
    '/_protected/administration/_layout/role/_layout': {
      id: '/_protected/administration/_layout/role/_layout'
      path: '/role'
      fullPath: '/administration/role'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRoleLayoutRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoute
    }
    '/_protected/masters/organization/_layout/branch/': {
      id: '/_protected/masters/organization/_layout/branch/'
      path: '/branch'
      fullPath: '/masters/organization/branch/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutBranchIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/administration/_layout/user/_layout/': {
      id: '/_protected/administration/_layout/user/_layout/'
      path: '/'
      fullPath: '/administration/user/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutUserLayoutIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutUserLayoutRoute
    }
    '/_protected/administration/_layout/role/_layout/': {
      id: '/_protected/administration/_layout/role/_layout/'
      path: '/'
      fullPath: '/administration/role/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRoleLayoutIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoleLayoutRoute
    }
    '/_protected/masters/organization/_layout/state/_layout': {
      id: '/_protected/masters/organization/_layout/state/_layout'
      path: '/state'
      fullPath: '/masters/organization/state'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/masters/organization/_layout/fiscal_year/_layout': {
      id: '/_protected/masters/organization/_layout/fiscal_year/_layout'
      path: '/fiscal_year'
      fullPath: '/masters/organization/fiscal_year'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/masters/organization/_layout/currency/_layout': {
      id: '/_protected/masters/organization/_layout/currency/_layout'
      path: '/currency'
      fullPath: '/masters/organization/currency'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/masters/organization/_layout/country/_layout': {
      id: '/_protected/masters/organization/_layout/country/_layout'
      path: '/country'
      fullPath: '/masters/organization/country'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/masters/organization/_layout/company/_layout': {
      id: '/_protected/masters/organization/_layout/company/_layout'
      path: '/company'
      fullPath: '/masters/organization/company'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutRoute
    }
    '/_protected/administration/_layout/user/_layout/$id': {
      id: '/_protected/administration/_layout/user/_layout/$id'
      path: '/$id'
      fullPath: '/administration/user/$id'
      preLoaderRoute: typeof ProtectedAdministrationLayoutUserLayoutIdRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutUserLayoutRoute
    }
    '/_protected/masters/organization/_layout/state/_layout/': {
      id: '/_protected/masters/organization/_layout/state/_layout/'
      path: '/'
      fullPath: '/masters/organization/state/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutRoute
    }
    '/_protected/masters/organization/_layout/fiscal_year/_layout/': {
      id: '/_protected/masters/organization/_layout/fiscal_year/_layout/'
      path: '/'
      fullPath: '/masters/organization/fiscal_year/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute
    }
    '/_protected/masters/organization/_layout/currency/_layout/': {
      id: '/_protected/masters/organization/_layout/currency/_layout/'
      path: '/'
      fullPath: '/masters/organization/currency/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRoute
    }
    '/_protected/masters/organization/_layout/country/_layout/': {
      id: '/_protected/masters/organization/_layout/country/_layout/'
      path: '/'
      fullPath: '/masters/organization/country/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutRoute
    }
    '/_protected/masters/organization/_layout/company/_layout/': {
      id: '/_protected/masters/organization/_layout/company/_layout/'
      path: '/'
      fullPath: '/masters/organization/company/'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutIndexRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutRoute
    }
    '/_protected/masters/organization/_layout/state/_layout/$id': {
      id: '/_protected/masters/organization/_layout/state/_layout/$id'
      path: '/$id'
      fullPath: '/masters/organization/state/$id'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutIdRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutRoute
    }
    '/_protected/masters/organization/_layout/fiscal_year/_layout/$id': {
      id: '/_protected/masters/organization/_layout/fiscal_year/_layout/$id'
      path: '/$id'
      fullPath: '/masters/organization/fiscal_year/$id'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute
    }
    '/_protected/masters/organization/_layout/currency/_layout/$id': {
      id: '/_protected/masters/organization/_layout/currency/_layout/$id'
      path: '/$id'
      fullPath: '/masters/organization/currency/$id'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIdRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRoute
    }
    '/_protected/masters/organization/_layout/country/_layout/$id': {
      id: '/_protected/masters/organization/_layout/country/_layout/$id'
      path: '/$id'
      fullPath: '/masters/organization/country/$id'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutIdRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutRoute
    }
    '/_protected/masters/organization/_layout/company/_layout/$id': {
      id: '/_protected/masters/organization/_layout/company/_layout/$id'
      path: '/$id'
      fullPath: '/masters/organization/company/$id'
      preLoaderRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutIdRouteImport
      parentRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutRoute
    }
    '/_protected/administration/_layout/role/_layout/$id/_module': {
      id: '/_protected/administration/_layout/role/_layout/$id/_module'
      path: '/$id'
      fullPath: '/administration/role/$id'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoleLayoutRoute
    }
    '/_protected/administration/_layout/role/_layout/$id/_module/': {
      id: '/_protected/administration/_layout/role/_layout/$id/_module/'
      path: '/'
      fullPath: '/administration/role/$id/'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRoute
    }
    '/_protected/administration/_layout/role/_layout/$id/_module/$moduleid': {
      id: '/_protected/administration/_layout/role/_layout/$id/_module/$moduleid'
      path: '/$moduleid'
      fullPath: '/administration/role/$id/$moduleid'
      preLoaderRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRouteImport
      parentRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRoute
    }
  }
}

interface ProtectedAdministrationLayoutRoleLayoutIdModuleRouteChildren {
  ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute
  ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute
}

const ProtectedAdministrationLayoutRoleLayoutIdModuleRouteChildren: ProtectedAdministrationLayoutRoleLayoutIdModuleRouteChildren =
  {
    ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute:
      ProtectedAdministrationLayoutRoleLayoutIdModuleModuleidRoute,
    ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute:
      ProtectedAdministrationLayoutRoleLayoutIdModuleIndexRoute,
  }

const ProtectedAdministrationLayoutRoleLayoutIdModuleRouteWithChildren =
  ProtectedAdministrationLayoutRoleLayoutIdModuleRoute._addFileChildren(
    ProtectedAdministrationLayoutRoleLayoutIdModuleRouteChildren,
  )

interface ProtectedAdministrationLayoutRoleLayoutRouteChildren {
  ProtectedAdministrationLayoutRoleLayoutIndexRoute: typeof ProtectedAdministrationLayoutRoleLayoutIndexRoute
  ProtectedAdministrationLayoutRoleLayoutIdModuleRoute: typeof ProtectedAdministrationLayoutRoleLayoutIdModuleRouteWithChildren
}

const ProtectedAdministrationLayoutRoleLayoutRouteChildren: ProtectedAdministrationLayoutRoleLayoutRouteChildren =
  {
    ProtectedAdministrationLayoutRoleLayoutIndexRoute:
      ProtectedAdministrationLayoutRoleLayoutIndexRoute,
    ProtectedAdministrationLayoutRoleLayoutIdModuleRoute:
      ProtectedAdministrationLayoutRoleLayoutIdModuleRouteWithChildren,
  }

const ProtectedAdministrationLayoutRoleLayoutRouteWithChildren =
  ProtectedAdministrationLayoutRoleLayoutRoute._addFileChildren(
    ProtectedAdministrationLayoutRoleLayoutRouteChildren,
  )

interface ProtectedAdministrationLayoutUserLayoutRouteChildren {
  ProtectedAdministrationLayoutUserLayoutIdRoute: typeof ProtectedAdministrationLayoutUserLayoutIdRoute
  ProtectedAdministrationLayoutUserLayoutIndexRoute: typeof ProtectedAdministrationLayoutUserLayoutIndexRoute
}

const ProtectedAdministrationLayoutUserLayoutRouteChildren: ProtectedAdministrationLayoutUserLayoutRouteChildren =
  {
    ProtectedAdministrationLayoutUserLayoutIdRoute:
      ProtectedAdministrationLayoutUserLayoutIdRoute,
    ProtectedAdministrationLayoutUserLayoutIndexRoute:
      ProtectedAdministrationLayoutUserLayoutIndexRoute,
  }

const ProtectedAdministrationLayoutUserLayoutRouteWithChildren =
  ProtectedAdministrationLayoutUserLayoutRoute._addFileChildren(
    ProtectedAdministrationLayoutUserLayoutRouteChildren,
  )

interface ProtectedAdministrationLayoutRouteChildren {
  ProtectedAdministrationLayoutRoleLayoutRoute: typeof ProtectedAdministrationLayoutRoleLayoutRouteWithChildren
  ProtectedAdministrationLayoutUserLayoutRoute: typeof ProtectedAdministrationLayoutUserLayoutRouteWithChildren
  ProtectedAdministrationLayoutApp_moduleIndexRoute: typeof ProtectedAdministrationLayoutApp_moduleIndexRoute
  ProtectedAdministrationLayoutApp_module_featureIndexRoute: typeof ProtectedAdministrationLayoutApp_module_featureIndexRoute
  ProtectedAdministrationLayoutPermissionIndexRoute: typeof ProtectedAdministrationLayoutPermissionIndexRoute
}

const ProtectedAdministrationLayoutRouteChildren: ProtectedAdministrationLayoutRouteChildren =
  {
    ProtectedAdministrationLayoutRoleLayoutRoute:
      ProtectedAdministrationLayoutRoleLayoutRouteWithChildren,
    ProtectedAdministrationLayoutUserLayoutRoute:
      ProtectedAdministrationLayoutUserLayoutRouteWithChildren,
    ProtectedAdministrationLayoutApp_moduleIndexRoute:
      ProtectedAdministrationLayoutApp_moduleIndexRoute,
    ProtectedAdministrationLayoutApp_module_featureIndexRoute:
      ProtectedAdministrationLayoutApp_module_featureIndexRoute,
    ProtectedAdministrationLayoutPermissionIndexRoute:
      ProtectedAdministrationLayoutPermissionIndexRoute,
  }

const ProtectedAdministrationLayoutRouteWithChildren =
  ProtectedAdministrationLayoutRoute._addFileChildren(
    ProtectedAdministrationLayoutRouteChildren,
  )

interface ProtectedauthUserFiscalYearLayoutRouteChildren {
  ProtectedauthUserFiscalYearLayoutIndexRoute: typeof ProtectedauthUserFiscalYearLayoutIndexRoute
}

const ProtectedauthUserFiscalYearLayoutRouteChildren: ProtectedauthUserFiscalYearLayoutRouteChildren =
  {
    ProtectedauthUserFiscalYearLayoutIndexRoute:
      ProtectedauthUserFiscalYearLayoutIndexRoute,
  }

const ProtectedauthUserFiscalYearLayoutRouteWithChildren =
  ProtectedauthUserFiscalYearLayoutRoute._addFileChildren(
    ProtectedauthUserFiscalYearLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutCompanyLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute
  ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute
}

const ProtectedMastersOrganizationLayoutCompanyLayoutRouteChildren: ProtectedMastersOrganizationLayoutCompanyLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute:
      ProtectedMastersOrganizationLayoutCompanyLayoutIdRoute,
    ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute:
      ProtectedMastersOrganizationLayoutCompanyLayoutIndexRoute,
  }

const ProtectedMastersOrganizationLayoutCompanyLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutCompanyLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutCompanyLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutCountryLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutCountryLayoutIdRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutIdRoute
  ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute
}

const ProtectedMastersOrganizationLayoutCountryLayoutRouteChildren: ProtectedMastersOrganizationLayoutCountryLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutCountryLayoutIdRoute:
      ProtectedMastersOrganizationLayoutCountryLayoutIdRoute,
    ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute:
      ProtectedMastersOrganizationLayoutCountryLayoutIndexRoute,
  }

const ProtectedMastersOrganizationLayoutCountryLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutCountryLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutCountryLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutCurrencyLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute
  ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute
}

const ProtectedMastersOrganizationLayoutCurrencyLayoutRouteChildren: ProtectedMastersOrganizationLayoutCurrencyLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute:
      ProtectedMastersOrganizationLayoutCurrencyLayoutIdRoute,
    ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute:
      ProtectedMastersOrganizationLayoutCurrencyLayoutIndexRoute,
  }

const ProtectedMastersOrganizationLayoutCurrencyLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutCurrencyLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutCurrencyLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute
}

const ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteChildren: ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute:
      ProtectedMastersOrganizationLayoutFiscal_yearLayoutIdRoute,
    ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute:
      ProtectedMastersOrganizationLayoutFiscal_yearLayoutIndexRoute,
  }

const ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutStateLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutStateLayoutIdRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutIdRoute
  ProtectedMastersOrganizationLayoutStateLayoutIndexRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutIndexRoute
}

const ProtectedMastersOrganizationLayoutStateLayoutRouteChildren: ProtectedMastersOrganizationLayoutStateLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutStateLayoutIdRoute:
      ProtectedMastersOrganizationLayoutStateLayoutIdRoute,
    ProtectedMastersOrganizationLayoutStateLayoutIndexRoute:
      ProtectedMastersOrganizationLayoutStateLayoutIndexRoute,
  }

const ProtectedMastersOrganizationLayoutStateLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutStateLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutStateLayoutRouteChildren,
  )

interface ProtectedMastersOrganizationLayoutRouteChildren {
  ProtectedMastersOrganizationLayoutCompanyLayoutRoute: typeof ProtectedMastersOrganizationLayoutCompanyLayoutRouteWithChildren
  ProtectedMastersOrganizationLayoutCountryLayoutRoute: typeof ProtectedMastersOrganizationLayoutCountryLayoutRouteWithChildren
  ProtectedMastersOrganizationLayoutCurrencyLayoutRoute: typeof ProtectedMastersOrganizationLayoutCurrencyLayoutRouteWithChildren
  ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute: typeof ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteWithChildren
  ProtectedMastersOrganizationLayoutStateLayoutRoute: typeof ProtectedMastersOrganizationLayoutStateLayoutRouteWithChildren
  ProtectedMastersOrganizationLayoutBranchIndexRoute: typeof ProtectedMastersOrganizationLayoutBranchIndexRoute
}

const ProtectedMastersOrganizationLayoutRouteChildren: ProtectedMastersOrganizationLayoutRouteChildren =
  {
    ProtectedMastersOrganizationLayoutCompanyLayoutRoute:
      ProtectedMastersOrganizationLayoutCompanyLayoutRouteWithChildren,
    ProtectedMastersOrganizationLayoutCountryLayoutRoute:
      ProtectedMastersOrganizationLayoutCountryLayoutRouteWithChildren,
    ProtectedMastersOrganizationLayoutCurrencyLayoutRoute:
      ProtectedMastersOrganizationLayoutCurrencyLayoutRouteWithChildren,
    ProtectedMastersOrganizationLayoutFiscal_yearLayoutRoute:
      ProtectedMastersOrganizationLayoutFiscal_yearLayoutRouteWithChildren,
    ProtectedMastersOrganizationLayoutStateLayoutRoute:
      ProtectedMastersOrganizationLayoutStateLayoutRouteWithChildren,
    ProtectedMastersOrganizationLayoutBranchIndexRoute:
      ProtectedMastersOrganizationLayoutBranchIndexRoute,
  }

const ProtectedMastersOrganizationLayoutRouteWithChildren =
  ProtectedMastersOrganizationLayoutRoute._addFileChildren(
    ProtectedMastersOrganizationLayoutRouteChildren,
  )

interface ProtectedRouteChildren {
  ProtectedProduct_launchboardRoute: typeof ProtectedProduct_launchboardRoute
  ProtectedSignOutRoute: typeof ProtectedSignOutRoute
  ProtectedauthChangePasswordRoute: typeof ProtectedauthChangePasswordRoute
  ProtectedAdministrationLayoutRoute: typeof ProtectedAdministrationLayoutRouteWithChildren
  ProtectedauthUserFiscalYearLayoutRoute: typeof ProtectedauthUserFiscalYearLayoutRouteWithChildren
  ProtectedfilerAssesseeAddRoute: typeof ProtectedfilerAssesseeAddRoute
  ProtectedfilerAssesseeEditRoute: typeof ProtectedfilerAssesseeEditRoute
  ProtectedfilerAssesseeHeyassesseeRoute: typeof ProtectedfilerAssesseeHeyassesseeRoute
  ProtectedMastersOrganizationLayoutRoute: typeof ProtectedMastersOrganizationLayoutRouteWithChildren
  ProtectedauthAddtaxformIndexRoute: typeof ProtectedauthAddtaxformIndexRoute
  ProtectedauthMemberIndexRoute: typeof ProtectedauthMemberIndexRoute
  ProtectedauthVerifyPanIndexRoute: typeof ProtectedauthVerifyPanIndexRoute
  ProtectedfilerDashboardIndexRoute: typeof ProtectedfilerDashboardIndexRoute
  ProtectedfilerDashboard_filerIndexRoute: typeof ProtectedfilerDashboard_filerIndexRoute
  ProtectedfilerDepartment_add_clientIndexRoute: typeof ProtectedfilerDepartment_add_clientIndexRoute
  ProtectedfilerStartIndexRoute: typeof ProtectedfilerStartIndexRoute
  ProtectedSupportHelpIndexRoute: typeof ProtectedSupportHelpIndexRoute
  ProtectedauthProfileIndexRoute: typeof ProtectedauthProfileIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedProduct_launchboardRoute: ProtectedProduct_launchboardRoute,
  ProtectedSignOutRoute: ProtectedSignOutRoute,
  ProtectedauthChangePasswordRoute: ProtectedauthChangePasswordRoute,
  ProtectedAdministrationLayoutRoute:
    ProtectedAdministrationLayoutRouteWithChildren,
  ProtectedauthUserFiscalYearLayoutRoute:
    ProtectedauthUserFiscalYearLayoutRouteWithChildren,
  ProtectedfilerAssesseeAddRoute: ProtectedfilerAssesseeAddRoute,
  ProtectedfilerAssesseeEditRoute: ProtectedfilerAssesseeEditRoute,
  ProtectedfilerAssesseeHeyassesseeRoute:
    ProtectedfilerAssesseeHeyassesseeRoute,
  ProtectedMastersOrganizationLayoutRoute:
    ProtectedMastersOrganizationLayoutRouteWithChildren,
  ProtectedauthAddtaxformIndexRoute: ProtectedauthAddtaxformIndexRoute,
  ProtectedauthMemberIndexRoute: ProtectedauthMemberIndexRoute,
  ProtectedauthVerifyPanIndexRoute: ProtectedauthVerifyPanIndexRoute,
  ProtectedfilerDashboardIndexRoute: ProtectedfilerDashboardIndexRoute,
  ProtectedfilerDashboard_filerIndexRoute:
    ProtectedfilerDashboard_filerIndexRoute,
  ProtectedfilerDepartment_add_clientIndexRoute:
    ProtectedfilerDepartment_add_clientIndexRoute,
  ProtectedfilerStartIndexRoute: ProtectedfilerStartIndexRoute,
  ProtectedSupportHelpIndexRoute: ProtectedSupportHelpIndexRoute,
  ProtectedauthProfileIndexRoute: ProtectedauthProfileIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  authForgotPasswordLazyRoute: authForgotPasswordLazyRoute,
  authSignIn2LazyRoute: authSignIn2LazyRoute,
  authSigninLazyRoute: authSigninLazyRoute,
  errors401LazyRoute: errors401LazyRoute,
  errors403LazyRoute: errors403LazyRoute,
  errors404LazyRoute: errors404LazyRoute,
  errors500LazyRoute: errors500LazyRoute,
  errors503LazyRoute: errors503LazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
